# Site configuration

# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Jekyll collections settings
# 6. Site settings
# 7. Social links

# 1. Files excluded from Jekyll builds
exclude:
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - vendor

# 2. Installed Gems
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-default-layout
  - jekyll-archives
  - jemoji

# 3. Gem settings
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: Vivliostyle              # jekyll-seo-tag > Owners twitter username
author: Vivliostyle                  # jekyll-seo-tag > default author
social:                              # jekyll-seo-tag > social overrides
  name: Vivliostyle                  # jekyll-seo-tag > real name
  links:                             # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/Vivliostyle
    - https://www.facebook.com/Vivliostyle
    - https://github.com/vivliostyle
    # - https://www.linkedin.com/in/Vivliostyle
    # - https://plus.google.com/+Vivliostyle

# 4. Jekyll settings
permalink: pretty                # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Asia/Tokyo             # Timezone for blog posts and alike

# 5. Jekyll collections settings
defaults:
  - values:
      image: "/assets/default-social-image.png" # Default image for sharing
      lang: "en"
  - scope:
      path: "/ja/*"
    values:
      lang: "ja"
  - scope:
      type: "posts"
    values:
      permalink: /blog/:year/:month/:day/:title/
  - scope:
      path: "_posts/ja/*"
      type: "posts"
    values:
      lang: "ja"
      permalink: /ja/blog/:year/:month/:day/:title/
jekyll-archives:
  enabled:
    - tags
  layout: blog_tag
  permalinks:
    tag: '/blog/tag/:name/'

# 6. Site settings
encoding: utf-8                           # Make sure the encoding is right
lang: en                                  # Set the site language
title: "Vivliostyle"                      # Site name or title, also used in jekyll-seo-tag
logo: "/assets/vivliostyle-logo.svg"      # Site logo, also used in jekyll-seo-tag
description: "Vivliostyle — open source, web browser based CSS typesetting engine project" # Site description and default description, also used in jekyll-seo-tag
url: "https://vivliostyle.org"            # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/vivliostyle/vivliostyle.org"
avatarurl: "/assets/vivliostyle-icon.png" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 7. Social links
social_links:
  Twitter: https://twitter.com/Vivliostyle
  Facebook: https://www.facebook.com/Vivliostyle
  GitHub: https://github.com/vivliostyle
  link: https://vivliostyle.org
  RSS: /blog/feed.xml
  # LinkedIn: https://www.linkedin.com/in/Vivliostyle
  # Google+: https://plus.google.com/+Vivliostyle
