# TODO: versions

core:
  version: "v2.0.0"
  github: "https://github.com/vivliostyle/vivliostyle/tree/master/packages/core"
  thumbnail: "assets/project-core.png"
pub:
  # version: ""
  url: ""
  github: ""
  sample:
    ja: "/ja/samples/"
    en: "/samples/"
  thumbnail: "assets/project-pub.png"
cli:
  version: "v2.0.0"
  github: "https://github.com/vivliostyle/vivliostyle-cli"
  sample:
    ja: "https://vivliostyle.org/viewer/#x=https://vivliostyle.github.io/vivliostyle_doc/samples/gon/index.html"
    en: "https://vivliostyle.org/viewer/#x=https://vivliostyle.github.io/vivliostyle_doc/samples/gutenberg/Alice.html"
  thumbnail: "assets/project-cli.png"
viewer:
  version: "v2.0.0"
  url: "https://vivliostyle.org/viewer"
  github: "https://github.com/vivliostyle/vivliostyle/tree/master/packages/viewer"
  sample: "https://vivliostyle.org/viewer"
  thumbnail: "assets/project-viewer.png"
